/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceTermsRouteImport } from './routes/marketplace.terms'
import { Route as MarketplaceTaxiRouteImport } from './routes/marketplace.taxi'
import { Route as MarketplaceSocialRouteImport } from './routes/marketplace.social'
import { Route as MarketplaceSearchRouteImport } from './routes/marketplace.search'
import { Route as MarketplaceRidesRouteImport } from './routes/marketplace.rides'
import { Route as MarketplaceProfileRouteImport } from './routes/marketplace.profile'
import { Route as MarketplacePrivacyRouteImport } from './routes/marketplace.privacy'
import { Route as MarketplaceOrdersRouteImport } from './routes/marketplace.orders'
import { Route as MarketplaceErrandsRouteImport } from './routes/marketplace.errands'
import { Route as MarketplaceDirectoryRouteImport } from './routes/marketplace.directory'
import { Route as MarketplaceCheckoutRouteImport } from './routes/marketplace.checkout'
import { Route as MarketplaceCartRouteImport } from './routes/marketplace.cart'
import { Route as MarketplaceAddressesRouteImport } from './routes/marketplace.addresses'
import { Route as MarketplaceBusinessIndexRouteImport } from './routes/marketplace.business.index'
import { Route as MarketplaceStoreStoreIdRouteImport } from './routes/marketplace.store.$storeId'
import { Route as MarketplaceOrdersOrderIdRouteImport } from './routes/marketplace.orders.$orderId'
import { Route as MarketplaceBusinessVehiclesRouteImport } from './routes/marketplace.business.vehicles'
import { Route as MarketplaceBusinessPropertyIdRouteImport } from './routes/marketplace.business.$propertyId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceTermsRoute = MarketplaceTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceTaxiRoute = MarketplaceTaxiRouteImport.update({
  id: '/taxi',
  path: '/taxi',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceSocialRoute = MarketplaceSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceSearchRoute = MarketplaceSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceRidesRoute = MarketplaceRidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceProfileRoute = MarketplaceProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplacePrivacyRoute = MarketplacePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceOrdersRoute = MarketplaceOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceErrandsRoute = MarketplaceErrandsRouteImport.update({
  id: '/errands',
  path: '/errands',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceDirectoryRoute = MarketplaceDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceCheckoutRoute = MarketplaceCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceCartRoute = MarketplaceCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceAddressesRoute = MarketplaceAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceBusinessIndexRoute =
  MarketplaceBusinessIndexRouteImport.update({
    id: '/business/',
    path: '/business/',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const MarketplaceStoreStoreIdRoute = MarketplaceStoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceOrdersOrderIdRoute =
  MarketplaceOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => MarketplaceOrdersRoute,
  } as any)
const MarketplaceBusinessVehiclesRoute =
  MarketplaceBusinessVehiclesRouteImport.update({
    id: '/business/vehicles',
    path: '/business/vehicles',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const MarketplaceBusinessPropertyIdRoute =
  MarketplaceBusinessPropertyIdRouteImport.update({
    id: '/business/$propertyId',
    path: '/business/$propertyId',
    getParentRoute: () => MarketplaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/signup': typeof SignupRoute
  '/marketplace/addresses': typeof MarketplaceAddressesRoute
  '/marketplace/cart': typeof MarketplaceCartRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/directory': typeof MarketplaceDirectoryRoute
  '/marketplace/errands': typeof MarketplaceErrandsRoute
  '/marketplace/orders': typeof MarketplaceOrdersRouteWithChildren
  '/marketplace/privacy': typeof MarketplacePrivacyRoute
  '/marketplace/profile': typeof MarketplaceProfileRoute
  '/marketplace/rides': typeof MarketplaceRidesRoute
  '/marketplace/search': typeof MarketplaceSearchRoute
  '/marketplace/social': typeof MarketplaceSocialRoute
  '/marketplace/taxi': typeof MarketplaceTaxiRoute
  '/marketplace/terms': typeof MarketplaceTermsRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/business/$propertyId': typeof MarketplaceBusinessPropertyIdRoute
  '/marketplace/business/vehicles': typeof MarketplaceBusinessVehiclesRoute
  '/marketplace/orders/$orderId': typeof MarketplaceOrdersOrderIdRoute
  '/marketplace/store/$storeId': typeof MarketplaceStoreStoreIdRoute
  '/marketplace/business/': typeof MarketplaceBusinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/marketplace/addresses': typeof MarketplaceAddressesRoute
  '/marketplace/cart': typeof MarketplaceCartRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/directory': typeof MarketplaceDirectoryRoute
  '/marketplace/errands': typeof MarketplaceErrandsRoute
  '/marketplace/orders': typeof MarketplaceOrdersRouteWithChildren
  '/marketplace/privacy': typeof MarketplacePrivacyRoute
  '/marketplace/profile': typeof MarketplaceProfileRoute
  '/marketplace/rides': typeof MarketplaceRidesRoute
  '/marketplace/search': typeof MarketplaceSearchRoute
  '/marketplace/social': typeof MarketplaceSocialRoute
  '/marketplace/taxi': typeof MarketplaceTaxiRoute
  '/marketplace/terms': typeof MarketplaceTermsRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/marketplace/business/$propertyId': typeof MarketplaceBusinessPropertyIdRoute
  '/marketplace/business/vehicles': typeof MarketplaceBusinessVehiclesRoute
  '/marketplace/orders/$orderId': typeof MarketplaceOrdersOrderIdRoute
  '/marketplace/store/$storeId': typeof MarketplaceStoreStoreIdRoute
  '/marketplace/business': typeof MarketplaceBusinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/signup': typeof SignupRoute
  '/marketplace/addresses': typeof MarketplaceAddressesRoute
  '/marketplace/cart': typeof MarketplaceCartRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/marketplace/directory': typeof MarketplaceDirectoryRoute
  '/marketplace/errands': typeof MarketplaceErrandsRoute
  '/marketplace/orders': typeof MarketplaceOrdersRouteWithChildren
  '/marketplace/privacy': typeof MarketplacePrivacyRoute
  '/marketplace/profile': typeof MarketplaceProfileRoute
  '/marketplace/rides': typeof MarketplaceRidesRoute
  '/marketplace/search': typeof MarketplaceSearchRoute
  '/marketplace/social': typeof MarketplaceSocialRoute
  '/marketplace/taxi': typeof MarketplaceTaxiRoute
  '/marketplace/terms': typeof MarketplaceTermsRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/business/$propertyId': typeof MarketplaceBusinessPropertyIdRoute
  '/marketplace/business/vehicles': typeof MarketplaceBusinessVehiclesRoute
  '/marketplace/orders/$orderId': typeof MarketplaceOrdersOrderIdRoute
  '/marketplace/store/$storeId': typeof MarketplaceStoreStoreIdRoute
  '/marketplace/business/': typeof MarketplaceBusinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/marketplace'
    | '/signup'
    | '/marketplace/addresses'
    | '/marketplace/cart'
    | '/marketplace/checkout'
    | '/marketplace/directory'
    | '/marketplace/errands'
    | '/marketplace/orders'
    | '/marketplace/privacy'
    | '/marketplace/profile'
    | '/marketplace/rides'
    | '/marketplace/search'
    | '/marketplace/social'
    | '/marketplace/taxi'
    | '/marketplace/terms'
    | '/marketplace/'
    | '/marketplace/business/$propertyId'
    | '/marketplace/business/vehicles'
    | '/marketplace/orders/$orderId'
    | '/marketplace/store/$storeId'
    | '/marketplace/business/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/marketplace/addresses'
    | '/marketplace/cart'
    | '/marketplace/checkout'
    | '/marketplace/directory'
    | '/marketplace/errands'
    | '/marketplace/orders'
    | '/marketplace/privacy'
    | '/marketplace/profile'
    | '/marketplace/rides'
    | '/marketplace/search'
    | '/marketplace/social'
    | '/marketplace/taxi'
    | '/marketplace/terms'
    | '/marketplace'
    | '/marketplace/business/$propertyId'
    | '/marketplace/business/vehicles'
    | '/marketplace/orders/$orderId'
    | '/marketplace/store/$storeId'
    | '/marketplace/business'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/marketplace'
    | '/signup'
    | '/marketplace/addresses'
    | '/marketplace/cart'
    | '/marketplace/checkout'
    | '/marketplace/directory'
    | '/marketplace/errands'
    | '/marketplace/orders'
    | '/marketplace/privacy'
    | '/marketplace/profile'
    | '/marketplace/rides'
    | '/marketplace/search'
    | '/marketplace/social'
    | '/marketplace/taxi'
    | '/marketplace/terms'
    | '/marketplace/'
    | '/marketplace/business/$propertyId'
    | '/marketplace/business/vehicles'
    | '/marketplace/orders/$orderId'
    | '/marketplace/store/$storeId'
    | '/marketplace/business/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/terms': {
      id: '/marketplace/terms'
      path: '/terms'
      fullPath: '/marketplace/terms'
      preLoaderRoute: typeof MarketplaceTermsRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/taxi': {
      id: '/marketplace/taxi'
      path: '/taxi'
      fullPath: '/marketplace/taxi'
      preLoaderRoute: typeof MarketplaceTaxiRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/social': {
      id: '/marketplace/social'
      path: '/social'
      fullPath: '/marketplace/social'
      preLoaderRoute: typeof MarketplaceSocialRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/search': {
      id: '/marketplace/search'
      path: '/search'
      fullPath: '/marketplace/search'
      preLoaderRoute: typeof MarketplaceSearchRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/rides': {
      id: '/marketplace/rides'
      path: '/rides'
      fullPath: '/marketplace/rides'
      preLoaderRoute: typeof MarketplaceRidesRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/profile': {
      id: '/marketplace/profile'
      path: '/profile'
      fullPath: '/marketplace/profile'
      preLoaderRoute: typeof MarketplaceProfileRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/privacy': {
      id: '/marketplace/privacy'
      path: '/privacy'
      fullPath: '/marketplace/privacy'
      preLoaderRoute: typeof MarketplacePrivacyRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/orders': {
      id: '/marketplace/orders'
      path: '/orders'
      fullPath: '/marketplace/orders'
      preLoaderRoute: typeof MarketplaceOrdersRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/errands': {
      id: '/marketplace/errands'
      path: '/errands'
      fullPath: '/marketplace/errands'
      preLoaderRoute: typeof MarketplaceErrandsRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/directory': {
      id: '/marketplace/directory'
      path: '/directory'
      fullPath: '/marketplace/directory'
      preLoaderRoute: typeof MarketplaceDirectoryRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/checkout': {
      id: '/marketplace/checkout'
      path: '/checkout'
      fullPath: '/marketplace/checkout'
      preLoaderRoute: typeof MarketplaceCheckoutRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/cart': {
      id: '/marketplace/cart'
      path: '/cart'
      fullPath: '/marketplace/cart'
      preLoaderRoute: typeof MarketplaceCartRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/addresses': {
      id: '/marketplace/addresses'
      path: '/addresses'
      fullPath: '/marketplace/addresses'
      preLoaderRoute: typeof MarketplaceAddressesRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/business/': {
      id: '/marketplace/business/'
      path: '/business'
      fullPath: '/marketplace/business/'
      preLoaderRoute: typeof MarketplaceBusinessIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/store/$storeId': {
      id: '/marketplace/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/marketplace/store/$storeId'
      preLoaderRoute: typeof MarketplaceStoreStoreIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/orders/$orderId': {
      id: '/marketplace/orders/$orderId'
      path: '/$orderId'
      fullPath: '/marketplace/orders/$orderId'
      preLoaderRoute: typeof MarketplaceOrdersOrderIdRouteImport
      parentRoute: typeof MarketplaceOrdersRoute
    }
    '/marketplace/business/vehicles': {
      id: '/marketplace/business/vehicles'
      path: '/business/vehicles'
      fullPath: '/marketplace/business/vehicles'
      preLoaderRoute: typeof MarketplaceBusinessVehiclesRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/business/$propertyId': {
      id: '/marketplace/business/$propertyId'
      path: '/business/$propertyId'
      fullPath: '/marketplace/business/$propertyId'
      preLoaderRoute: typeof MarketplaceBusinessPropertyIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface MarketplaceOrdersRouteChildren {
  MarketplaceOrdersOrderIdRoute: typeof MarketplaceOrdersOrderIdRoute
}

const MarketplaceOrdersRouteChildren: MarketplaceOrdersRouteChildren = {
  MarketplaceOrdersOrderIdRoute: MarketplaceOrdersOrderIdRoute,
}

const MarketplaceOrdersRouteWithChildren =
  MarketplaceOrdersRoute._addFileChildren(MarketplaceOrdersRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceAddressesRoute: typeof MarketplaceAddressesRoute
  MarketplaceCartRoute: typeof MarketplaceCartRoute
  MarketplaceCheckoutRoute: typeof MarketplaceCheckoutRoute
  MarketplaceDirectoryRoute: typeof MarketplaceDirectoryRoute
  MarketplaceErrandsRoute: typeof MarketplaceErrandsRoute
  MarketplaceOrdersRoute: typeof MarketplaceOrdersRouteWithChildren
  MarketplacePrivacyRoute: typeof MarketplacePrivacyRoute
  MarketplaceProfileRoute: typeof MarketplaceProfileRoute
  MarketplaceRidesRoute: typeof MarketplaceRidesRoute
  MarketplaceSearchRoute: typeof MarketplaceSearchRoute
  MarketplaceSocialRoute: typeof MarketplaceSocialRoute
  MarketplaceTaxiRoute: typeof MarketplaceTaxiRoute
  MarketplaceTermsRoute: typeof MarketplaceTermsRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceBusinessPropertyIdRoute: typeof MarketplaceBusinessPropertyIdRoute
  MarketplaceBusinessVehiclesRoute: typeof MarketplaceBusinessVehiclesRoute
  MarketplaceStoreStoreIdRoute: typeof MarketplaceStoreStoreIdRoute
  MarketplaceBusinessIndexRoute: typeof MarketplaceBusinessIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceAddressesRoute: MarketplaceAddressesRoute,
  MarketplaceCartRoute: MarketplaceCartRoute,
  MarketplaceCheckoutRoute: MarketplaceCheckoutRoute,
  MarketplaceDirectoryRoute: MarketplaceDirectoryRoute,
  MarketplaceErrandsRoute: MarketplaceErrandsRoute,
  MarketplaceOrdersRoute: MarketplaceOrdersRouteWithChildren,
  MarketplacePrivacyRoute: MarketplacePrivacyRoute,
  MarketplaceProfileRoute: MarketplaceProfileRoute,
  MarketplaceRidesRoute: MarketplaceRidesRoute,
  MarketplaceSearchRoute: MarketplaceSearchRoute,
  MarketplaceSocialRoute: MarketplaceSocialRoute,
  MarketplaceTaxiRoute: MarketplaceTaxiRoute,
  MarketplaceTermsRoute: MarketplaceTermsRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceBusinessPropertyIdRoute: MarketplaceBusinessPropertyIdRoute,
  MarketplaceBusinessVehiclesRoute: MarketplaceBusinessVehiclesRoute,
  MarketplaceStoreStoreIdRoute: MarketplaceStoreStoreIdRoute,
  MarketplaceBusinessIndexRoute: MarketplaceBusinessIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
